"""add Department

Revision ID: 10073c2f20ae
Revises: bf7c071f388b
Create Date: 2024-04-03 23:16:05.455764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10073c2f20ae'
down_revision = 'bf7c071f388b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    # ### end Alembic commands ###
