"""rename address

Revision ID: 5cb4359344cf
Revises: a84f86e9c6c4
Create Date: 2024-04-04 07:49:12.563881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cb4359344cf'
down_revision = 'a84f86e9c6c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departments', schema=None) as batch_op:
       op.alter_column('departments', 'address',  new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departments', schema=None) as batch_op:
        op.alter_column('departments', 'location',  new_column_name='address')
    # ### end Alembic commands ###
